### PR TITLE
Add store method to komoju gateway

### PR DESCRIPTION
**Pull request by miyazawadegica**
ref: https://github.com/shioyama/active_merchant/blob/komoju_store/lib/active_merchant/billing/gateways/komoju.rb#L44

### CODE REVIEW

**Comment by degicat** [comment]
@camelmasa Please review this.

**Comment by camelmasa** [comment]
LGTM 👍

**Comment by miyazawadegica** [comment]
@camelmasa thanks. I'll merge this.

**Comment by miyazawadegica** [comment]
@shioyama Could you merge this as I have no permission to do so?

**Pull request merged**
