### PR TITLE
Fix 504 error message

### PR DESCRIPTION
**Pull request by shioyama**

### CODE REVIEW

**Comment by degicat** [comment]
@rramsden Please review this.

**Comment by rramsden** [comment]
@shioyama I don't think the translation will work here unless you add the locale to Basecamp.
The key is namespaced i.e. `en.spree.payment_processing_error`

**Comment by shioyama** [comment]
I think it works in Spree 1.3: https://github.com/degica/spree_i18n/blob/e3eae159c76812a52985b7e4deedea4144d3f502/config/locales/ja/ja.yml#L739

**Comment by rramsden** [comment]
Okay, LGTM 👍

**Comment by shioyama** [comment]
Thanks!

**Comment by rramsden** [comment]
You could also... default: `` but... this is supposed to be a temporary fix anyway until we fix the CDN

**Comment by shioyama** [comment]
Yes I thought about that... you're right that should be there.

**Pull request merged**
