### PR TITLE
Add Komoju gateway.

### PR DESCRIPTION
**Pull request by shioyama**

### CODE REVIEW

**Comment by rramsden** [comment]
This is old code, we don't use the Komoju client anymore for making API requests.

**Comment by shioyama** [comment]
Yeah I figured it didn't matter since this is just for Degica.

**Comment by k2nr** [comment]
please use the latest commit https://github.com/Shopify/active_merchant/pull/1638
you should cherry-pick only one commit

**Comment by shioyama** [comment]
@k2nr done

**Comment by k2nr** [comment]
thanks LGTM :+1:

**Comment by k2nr** [comment]
oops I found a bug in the test code... will fix now sorry

**Comment by shioyama** [comment]
@k2nr ok I'll re-cherry-pick it when it's fixed.

**Comment by k2nr** [comment]
force-pushed to the upstream PR. just changed `description` => `:description` https://github.com/Shopify/active_merchant/pull/1638/files#diff-c22000b6496cc7b789b7cd04b6e05587R16

**Comment by shioyama** [comment]
ok fixed it here too.

**Comment by k2nr** [comment]
`Response#error_code` was [added after Degica forked the repo](https://github.com/Shopify/active_merchant/commit/1a0c650). we should remove `error_code` related code from komoju gateway

**Comment by shioyama** [comment]
@k2nr I just cherry-picked the missing commit

**Comment by shioyama** [comment]
@k2nr if tests fail we can just remove it from this fork, but I'd prefer to have it for debugging and I don't want to actually rebase this because it would be a lot of trouble for little gain.

**Comment by shioyama** [comment]
oh well, seems it failed...

**Comment by k2nr** [comment]
https://github.com/shioyama/active_merchant/commit/970dd6b777fea69b5f3e87d1baa53c24b7e4d7da#commitcomment-10580857

**Comment by shioyama** [comment]
Cool passed!

**Comment by k2nr** [comment]
:+1:

**Pull request merged**
