### PR TITLE
Update komoju gateway

### PR DESCRIPTION
**Pull request by camelmasa**
I synced repo with `komoju/active_merchant`.
We can use `refund` and `fraud_details`.

### CODE REVIEW

**Comment by degicat** [comment]
@miyazawadegica Please review this.

**Comment by camelmasa** [comment]
@miyazawadegica sorry, my description wasn't enough.

``` rb
require "active_merchant"

cc = ActiveMerchant::Billing::CreditCard.new(
    :first_name => 'Steve',
    :last_name  => 'Smith',
    :month      => '9',
    :year       => '2017',
    :brand      => 'visa',
    :number     => '4123111111111083',
    :verification_value => '444'
    )

gateway = ActiveMerchant::Billing::KomojuGateway.new(login: LOGIN, test: true)

# fraud check
gateway.purchase(100, cc)



cc = ActiveMerchant::Billing::CreditCard.new(
    :first_name => 'Steve',
    :last_name  => 'Smith',
    :month      => '9',
    :year       => '2017',
    :brand      => 'visa',
    :number     => '4111111111111111',
    :verification_value => '444'
    )

result = gateway.purchase(100, cc)

# refund check
gateway.refund(100, result.params["id"])
```

We can check "fraud check" and refunding by above.

**Comment by miyazawadegica** [comment]
:+1:

**Comment by camelmasa** [comment]
@miyazawadegica Thank you for reviewing.

@shioyama Please merge this.

**Pull request merged**
