### PR TITLE
Fix missing email and add missing specs

### PR DESCRIPTION
**Pull request by shioyama**
Specs were not checking request json values at all, so added some assertions to sanity-check we're sending what we need to send. This is not thorough but it's enough for now I think.

### CODE REVIEW

**Comment by shioyama** [comment]
@rramsden can you review this?

For reference, here's the [comparison of commits](https://github.com/activemerchant/active_merchant/compare/f9f87b8c...degica:degica) where we lost the email option for non-CC payments.

**Comment by shioyama** [comment]
@rramsden ping

**Comment by rramsden** [comment]
LGTM

**Comment by shioyama** [comment]
Thanks!

**Pull request merged**
