### PR TITLE
Add metadata to purchase params in komoju gateway

### PR DESCRIPTION
**Pull request by miyazawadegica**

### CODE REVIEW

**Comment by shioyama** [comment]
@miyazawadegica can you rebase this on the latest? I fixed some issues in #17.

**Comment by miyazawadegica** [comment]
@shioyama thanks, I'll rebase this.

**Comment by miyazawadegica** [comment]
@shioyama please review this just one row change.

**Comment by shioyama** [comment]
LGTM!

**Comment by miyazawadegica** [comment]
thanks

**Pull request merged**
