### PR TITLE
Modify refund in komoju for partial refund.

### PR DESCRIPTION
**Pull request by miyazawadegica**

### CODE REVIEW

**Comment by degicat** [comment]
@k2nr Please review this.

**Comment by k2nr** [comment]
I think basecamp production is currently using ruby 2.1.x no?

**Comment by miyazawadegica** [comment]
Yes. bc2 uses ruby 2.1. we try to use ruby 2.1 here. As MiniTest is used in ruby 2.0 or higher, probably we need to modify many codes to pass test like test_helper. I tried a little, but some errors occurred. Should I use ruby 2.0 or higher to pass tests even if I take time?

I tried to modify some codes with ruby 2.1, but I could not pass test. we need to change test structure materially. At least it will take some days that we modify to do so.

**Comment by k2nr** [comment]
Thanks I understand. I think you don't need to update code just to make tests pass because `net-ssh` is only required in development environment.

Looks good to me :+1:

**Comment by miyazawadegica** [comment]
thanks.

**Comment by miyazawadegica** [comment]
@shioyama Can you merge this? I do not have a  permission to do so.

**Comment by miyazawadegica** [comment]
@shioyama ping

**Pull request merged**
